<?php get_header(); ?>
<?php
$avtospa_service_urls=array(
 'Автомойка'=>avtospa_service_page_url('Автомойка','/#services'),
 'Мойка двигателя'=>avtospa_service_page_url('Мойка двигателя','/#engine-wash'),
 'Шиномонтаж'=>avtospa_service_page_url('Шиномонтаж','/#tire-booking')
);
?>
<main id="content">
<section class="hero">
 <div class="hero-photo" aria-hidden="true"><img src="https://images.unsplash.com/photo-1781516153879-193e94f3d496?auto=format&fit=crop&fm=jpg&q=82&w=1800" alt=""></div>
 <div class="hero-photo-shade" aria-hidden="true"></div>
 <div class="container hero-grid">
  <div class="hero-copy">
   <span class="eyebrow">ЧИСТОТА • ЗАБОТА • ПРОФЕССИОНАЛИЗМ</span>
   <h1>АвтоСпа <span class="hero-h1-accent">Больше, чем просто мойка</span></h1>
   <p>Профессиональная автомойка, шиномонтаж и автосервис в Москве. Заботимся о вашем автомобиле 24 часа в сутки.</p>
   <div class="hero-buttons"><a class="button button-primary" href="#services">Записаться на мойку</a><a class="button button-secondary" href="#services">Все услуги&nbsp;›</a></div>
   <div class="hero-facts">
    <div class="hero-fact"><span class="fact-icon">◷</span><strong>Работаем<br>круглосуточно</strong></div>
    <div class="hero-fact"><span class="fact-icon">◆</span><strong>Качественные<br>материалы</strong></div>
    <div class="hero-fact"><span class="fact-icon">✓</span><strong>Опытные<br>специалисты</strong></div>
    <div class="hero-fact"><span class="fact-icon">⌁</span><strong>Забота<br>о вашем авто</strong></div>
   </div>
  </div>
 </div>
 <div class="container hero-shortcuts">
  <div class="hero-shortcuts-grid">
   <a class="shortcut" href="<?php echo esc_url($avtospa_service_urls['Автомойка']); ?>"><div class="shortcut-photo"><img src="https://images.unsplash.com/photo-1683647115932-b33455fe6a3e?auto=format&fit=crop&fm=jpg&q=82&w=900" alt="Автомойка АвтоСпа" loading="lazy" decoding="async"></div><div class="shortcut-copy"><h3>Автомойка ›</h3><p>Профессиональная мойка любого автомобиля</p></div></a>
   <a class="shortcut" href="<?php echo esc_url($avtospa_service_urls['Шиномонтаж']); ?>"><div class="shortcut-photo"><img src="https://images.unsplash.com/photo-1645445522156-9ac06bc7a767?auto=format&fit=crop&fm=jpg&q=82&w=900" alt="Шиномонтаж АвтоСпа" loading="lazy" decoding="async"></div><div class="shortcut-copy"><h3>Шиномонтаж ›</h3><p>Быстро, качественно, с гарантией</p></div></a>
   <a class="shortcut" href="https://xn----7sbbgabsz5cgqkebg.su/"><div class="shortcut-photo"><img src="https://images.unsplash.com/photo-1771340012319-0b4fca008b54?auto=format&fit=crop&fm=jpg&q=82&w=900" alt="Автосервис АвтоСпа" loading="lazy" decoding="async"></div><div class="shortcut-copy"><h3>Автосервис ›</h3><p>Диагностика и ремонт любой сложности</p></div></a>
   <a class="shortcut" href="<?php echo esc_url(home_url('/автомойка-цены/')); ?>"><div class="shortcut-photo"><img src="https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&fm=jpg&q=82&w=900" alt="Цены АвтоСпа" loading="lazy" decoding="async"></div><div class="shortcut-copy"><h3>Цены ›</h3><p>Прозрачные цены без скрытых платежей</p></div></a>
  </div>
 </div>
</section>

<section class="tire-booking-banner" id="tire-booking"><div class="container"><div class="tire-booking-card"><div class="tire-booking-visual"><img class="tire-service-image" src="<?php echo esc_url(get_template_directory_uri() . '/assets/img/tire-service.svg'); ?>" alt="Шиномонтаж АвтоСпа: автомобиль на подъёмнике и оборудование" loading="lazy" decoding="async" width="900" height="620"></div><div class="tire-booking-content"><span class="booking-kicker">АвтоСпа • Шиномонтаж</span><h2>Запишитесь на шиномонтаж</h2><p>Позвоните в АвтоСпа и согласуйте удобное время записи.</p><div class="booking-actions"><a class="button booking-button" href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>">📞 Записаться по телефону</a><a class="booking-phone" href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>"><?php echo esc_html(get_theme_mod('avtospa_phone','+7 916 299-98-59')); ?></a></div></div><div class="booking-badge"><strong>🛞</strong><span>Быстрая запись</span><small>по телефону</small></div></div></div></section>
<section id="services" class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">Профессиональный уход</span><h2>Услуги АвтоСпа</h2><p class="section-intro">Основные направления АвтоСпа: автомойка, мойка двигателя и шиномонтаж. Актуальные условия можно уточнить по телефону.</p></div></div><div class="cards">
<article class="card photo-card"><a class="service-card-link" href="<?php echo esc_url($avtospa_service_urls['Автомойка']); ?>"><div class="service-photo"><img src="https://images.unsplash.com/photo-1683647115932-b33455fe6a3e?auto=format&fit=crop&fm=jpg&q=82&w=1000" alt="Профессиональная автомойка АвтоСпа" loading="lazy" decoding="async"></div><div class="service-card-body"><h3>Автомойка</h3><p>Профессиональная мойка и уход за автомобилем.</p><span class="service-card-more">Открыть страницу услуги →</span></div></a></article>
<article class="card photo-card engine-wash-card"><a class="service-card-link" href="<?php echo esc_url($avtospa_service_urls['Мойка двигателя']); ?>"><div class="service-photo"><img src="https://images.unsplash.com/photo-1771340012319-0b4fca008b54?auto=format&fit=crop&fm=jpg&q=82&w=1000" alt="Работа с двигателем автомобиля" loading="lazy" decoding="async"></div><div class="service-card-body"><h3>Мойка двигателя</h3><p>Аккуратный профессиональный уход и обслуживание.</p><span class="service-card-more">Подробнее об услуге →</span></div></a></article>
<article class="card photo-card"><a class="service-card-link" href="<?php echo esc_url($avtospa_service_urls['Шиномонтаж']); ?>"><div class="service-photo"><img src="https://images.unsplash.com/photo-1645445522156-9ac06bc7a767?auto=format&fit=crop&fm=jpg&q=82&w=1000" alt="Шиномонтаж АвтоСпа" loading="lazy" decoding="async"></div><div class="service-card-body"><h3>Шиномонтаж</h3><p>Работа с колёсами, шинами и сезонной заменой.</p><span class="service-card-more">Записаться →</span></div></a></article>
</div></div></section>
<section id="engine-wash" class="section engine-section"><div class="container"><div class="engine-box"><div class="engine-copy"><span class="eyebrow">Отдельная услуга</span><h2>Мойка двигателя</h2><p>Мойка двигателя — отдельное направление АвтоСпа. Возможность выполнения услуги и актуальные условия уточняйте по телефону.</p><a class="button button-primary" href="<?php echo esc_url($avtospa_service_urls['Мойка двигателя']); ?>">Открыть страницу услуги</a></div><div class="engine-note"><span class="service-icon">🔧</span><strong>Мойка двигателя</strong><span>АвтоСпа • Москва</span></div></div></div></section>
<section id="tire-service" class="section tire-section"><div class="container"><div class="tire-box"><div><span class="eyebrow">Шиномонтаж</span><h2>Запись на шиномонтаж</h2><p>Позвоните в АвтоСпа, чтобы уточнить актуальные условия и согласовать удобное время.</p></div><div class="tire-actions"><a class="button button-primary tire-cta" href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>">📞 Записаться по телефону</a><a class="button tire-cta" href="<?php echo esc_url($avtospa_service_urls['Шиномонтаж']); ?>">Страница шиномонтажа</a></div></div></div></section>
<section class="section autotech-banner" id="autotech"><div class="container"><div class="autotech-banner-inner"><div class="autotech-copy"><span class="eyebrow">Отдельное направление</span><h2>Автосервис Автотех</h2><p>Ремонт, диагностика и техническое обслуживание автомобилей. Перейдите на отдельный сайт автосервиса, чтобы посмотреть услуги и записаться на ремонт.</p></div><a class="button button-primary" href="https://xn----7sbbgabsz5cgqkebg.su/" target="_blank" rel="noopener noreferrer">Автотех&nbsp;↗</a></div></div></section>
<section class="section reviews-location-section" id="reviews-location"><div class="container"><div class="section-head"><div><span class="eyebrow">АвтоСпа • Москва</span><h2>Отзывы и расположение</h2><p class="section-intro">Посмотрите отзывы в карточке АвтоСпа на Яндекс Картах и сразу проложите маршрут до автомойки.</p></div></div><div class="reviews-location-grid"><div class="yandex-review-card"><div class="review-card-head"><div><strong>Отзывы об АвтоСпа</strong><span>Яндекс Карты</span></div><a class="button button-primary" href="https://yandex.ru/maps/?ll=37.6288%2C55.8960&z=17&text=%D0%90%D0%B2%D1%82%D0%BE%D0%A1%D0%BF%D0%B0%2C%20%D0%9F%D0%BE%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%BE%D0%B5%D0%B7%D0%B4%2C%2018" target="_blank" rel="noopener noreferrer">Открыть Яндекс</a></div><iframe class="yandex-rating-widget" src="https://yandex.ru/sprav/widget/rating-badge/58733743477" title="Рейтинг АвтоСпа на Яндекс Картах" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><p class="review-note">Нажмите «Открыть Яндекс», чтобы перейти в карточку организации и посмотреть отзывы, рейтинг и информацию о месте.</p></div><div class="map-card"><div class="map-card-head"><div><strong>Где находится АвтоСпа</strong><span>Москва, Полярный проезд, 18, стр. 2</span></div><a class="map-link" href="https://yandex.ru/maps/?ll=37.6288%2C55.8960&z=17&pt=37.6288%2C55.8960%2Cpm2rdm&mode=search" target="_blank" rel="noopener noreferrer">Маршрут ↗</a></div><iframe class="yandex-map" src="https://yandex.ru/map-widget/v1/?ll=37.6288%2C55.8960&z=16&l=map&pt=37.6288%2C55.8960%2Cpm2rdm" title="Карта расположения АвтоСпа, Полярный проезд, 18, стр. 2, Москва" loading="lazy" allowfullscreen></iframe></div></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><div><h2>АвтоСпа в Москве</h2><p class="section-intro">Контактная информация и основные действия собраны в одном месте.</p></div></div><div class="benefits"><div class="benefit"><strong>Телефон</strong><span>Позвоните для записи и уточнения условий.</span></div><div class="benefit"><strong>Адрес</strong><span>Полярный проезд, 18, стр. 2, Москва.</span></div><div class="benefit"><strong>Шиномонтаж</strong><span>Отдельный блок для быстрой записи.</span></div><div class="benefit"><strong>Мойка двигателя</strong><span>Важная услуга автомойки, вынесенная на главную.</span></div></div></div></section>
<section id="contacts" class="section"><div class="container"><div class="contact-card contact-card-wide"><h2>Контакты АвтоСпа</h2><p>Позвоните, чтобы уточнить актуальные услуги и записаться.</p><div class="contact-row"><strong>Телефон</strong><a href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>"><?php echo esc_html(get_theme_mod('avtospa_phone','+7 916 299-98-59')); ?></a></div><div class="contact-row"><strong>Адрес</strong><span><?php echo esc_html(get_theme_mod('avtospa_address','Россия, Москва, Полярный проезд, 18, стр. 2')); ?></span></div><div class="contact-actions"><a class="button contact-map-button" href="#reviews-location">Посмотреть на карте</a><a class="button button-primary" href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>">📞 Позвонить в АвтоСпа</a></div></div></div></section>
<section class="section internal-links-section" aria-labelledby="internal-links-title"><div class="container"><div class="section-head"><div><span class="eyebrow">АвтоСпа • услуги</span><h2 id="internal-links-title">Услуги АвтоСпа в Москве</h2><p class="section-intro">Перейдите на отдельную страницу нужной услуги, чтобы посмотреть информацию и связаться с АвтоСпа.</p></div></div><div class="internal-links-grid"><a href="<?php echo esc_url($avtospa_service_urls['Автомойка']); ?>" class="internal-link-card"><span>🚿</span><strong>Автомойка</strong><small>Информация об автомойке в Москве →</small></a><a href="<?php echo esc_url($avtospa_service_urls['Мойка двигателя']); ?>" class="internal-link-card"><span>🔧</span><strong>Мойка двигателя</strong><small>Отдельная страница услуги →</small></a><a href="<?php echo esc_url($avtospa_service_urls['Шиномонтаж']); ?>" class="internal-link-card"><span>🛞</span><strong>Шиномонтаж</strong><small>Запись и условия услуги →</small></a><a href="#contacts" class="internal-link-card"><span>📍</span><strong>Контакты АвтоСпа</strong><small>Адрес и телефон →</small></a></div></div></section>
<section id="faq" class="section alt faq-section"><div class="container"><div class="section-head"><div><span class="eyebrow">АвтоСпа • вопросы</span><h2>Частые вопросы</h2><p class="section-intro">Короткие ответы о записи, расположении и актуальных услугах АвтоСпа.</p></div></div><div class="faq"><details><summary>Как записаться на шиномонтаж?</summary><p>Позвоните по номеру, указанному на сайте, и согласуйте удобное время.</p></details><details><summary>Где находится АвтоСпа?</summary><p>Москва, Полярный проезд, 18, стр. 2. Карта и кнопка маршрута находятся в блоке «Отзывы и расположение».</p></details><details><summary>Как посмотреть отзывы?</summary><p>Откройте карточку АвтоСпа в Яндекс Картах через блок отзывов на этой странице.</p></details><details><summary>Как узнать актуальный перечень услуг?</summary><p>Позвоните нам — специалисты уточнят доступные услуги и условия.</p></details></div></div></section>
</main>
<div class="mobile-booking-bar" aria-label="Быстрая запись"><a class="mobile-tire" href="<?php echo esc_url($avtospa_service_urls['Шиномонтаж']); ?>">🛞 Записаться</a><a class="mobile-call" href="tel:<?php echo esc_attr(avtospa_phone_href()); ?>">📞 Позвонить</a></div>
<?php get_footer(); ?>