<?php
/** АвтоСпа theme functions. */
if (!defined('ABSPATH')) { exit; }
function avtospa_setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',array('search-form','comment-form','comment-list','gallery','caption','style','script'));register_nav_menus(array('primary'=>'Основное меню','footer'=>'Меню в подвале'));} add_action('after_setup_theme','avtospa_setup');
function avtospa_assets(){
 $version=wp_get_theme()->get('Version');
 wp_enqueue_style('avtospa-style',get_stylesheet_uri(),array(),$version);
 wp_enqueue_style('avtospa-tire-booking',get_template_directory_uri().'/assets/css/tire-booking.css',array('avtospa-style'),$version);
 wp_enqueue_style('avtospa-header-premium',get_template_directory_uri().'/assets/css/header-premium.css',array('avtospa-style'),$version);
 wp_enqueue_style('avtospa-hero-premium',get_template_directory_uri().'/assets/css/hero-premium.css',array('avtospa-header-premium'),$version);
 wp_enqueue_style('avtospa-services-premium',get_template_directory_uri().'/assets/css/services-premium.css',array('avtospa-hero-premium'),$version);
 wp_enqueue_script('avtospa-navigation',get_template_directory_uri().'/assets/js/navigation.js',array(),$version,true);
 $interactive_css=':root{--avtospa-glow:rgba(24,183,173,.16)}.avtospa-progress{position:fixed;left:0;top:0;height:4px;width:0;background:linear-gradient(90deg,#18b7ad,#58b9e8,#ff9b52,#f39acb);z-index:9999;pointer-events:none;border-radius:0 99px 99px 0}.avtospa-reveal{opacity:0;transform:translateY(22px);transition:opacity .65s ease,transform .65s ease}.avtospa-reveal.is-visible{opacity:1;transform:none}.avtospa-floating-book{position:fixed;right:22px;bottom:22px;z-index:45;display:flex;align-items:center;gap:9px;padding:13px 17px;border-radius:999px;background:#ff9b52;color:#fff;font-weight:900;box-shadow:0 14px 32px rgba(255,155,82,.28);border:2px solid rgba(255,255,255,.9);transition:transform .2s ease,box-shadow .2s ease}.avtospa-floating-book:hover{transform:translateY(-4px);box-shadow:0 18px 38px rgba(255,155,82,.34)}.avtospa-floating-book .dot{width:9px;height:9px;border-radius:50%;background:#fff;box-shadow:0 0 0 6px rgba(255,255,255,.18);animation:avtospaPulse 1.8s infinite}.avtospa-nav-active{color:#18b7ad!important}@keyframes avtospaPulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(.72);opacity:.65}}@media(max-width:760px){.avtospa-floating-book{display:none}}@media(prefers-reduced-motion:reduce){.avtospa-reveal{opacity:1;transform:none;transition:none}.avtospa-floating-book .dot{animation:none}}';
 wp_add_inline_style('avtospa-style',$interactive_css);
 $interactive_js="document.addEventListener('DOMContentLoaded',function(){var bar=document.createElement('div');bar.className='avtospa-progress';bar.setAttribute('aria-hidden','true');document.body.appendChild(bar);var updateProgress=function(){var doc=document.documentElement;var max=doc.scrollHeight-window.innerHeight;bar.style.width=(max>0?(window.scrollY/max)*100:0)+'%';};window.addEventListener('scroll',updateProgress,{passive:true});updateProgress();var revealItems=document.querySelectorAll('.section,.tire-booking-banner,.hero-grid > div,.card,.benefit,.faq details,.contact-card,.autotech-banner-inner');if('IntersectionObserver' in window){revealItems.forEach(function(el){el.classList.add('avtospa-reveal')});var observer=new IntersectionObserver(function(entries,obs){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');obs.unobserve(entry.target)}})},{threshold:.12});revealItems.forEach(function(el){observer.observe(el)});}var sections=document.querySelectorAll('main section[id]');var navLinks=document.querySelectorAll('.main-nav a[href*=\"#\"]');if('IntersectionObserver' in window&&sections.length&&navLinks.length){var sectionObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){navLinks.forEach(function(link){link.classList.remove('avtospa-nav-active');if(link.getAttribute('href').indexOf('#'+entry.target.id)>-1){link.classList.add('avtospa-nav-active')}})}})},{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(function(section){sectionObserver.observe(section);});}});";
 wp_add_inline_script('avtospa-navigation',$interactive_js,'after');
} add_action('wp_enqueue_scripts','avtospa_assets');
function avtospa_floating_booking(){if(!is_front_page()){return;}echo '<a class="avtospa-floating-book" href="#tire-booking" aria-label="Записаться на шиномонтаж"><span class="dot" aria-hidden="true"></span>🛞 Записаться на шиномонтаж</a>';} add_action('wp_footer','avtospa_floating_booking',20);
function avtospa_customize_register($wp_customize){$wp_customize->add_section('avtospa_contacts',array('title'=>'АвтоСпа — контакты','priority'=>30));$wp_customize->add_setting('avtospa_phone',array('default'=>'+7 916 299-98-59','sanitize_callback'=>'sanitize_text_field'));$wp_customize->add_control('avtospa_phone',array('label'=>'Телефон','section'=>'avtospa_contacts','type'=>'text'));$wp_customize->add_setting('avtospa_address',array('default'=>'Россия, Москва, Полярный проезд, 18, стр. 2','sanitize_callback'=>'sanitize_text_field'));$wp_customize->add_control('avtospa_address',array('label'=>'Адрес','section'=>'avtospa_contacts','type'=>'text'));$wp_customize->add_setting('avtospa_whatsapp',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control('avtospa_whatsapp',array('label'=>'WhatsApp URL','section'=>'avtospa_contacts','type'=>'url'));$wp_customize->add_setting('avtospa_telegram',array('default'=>'','sanitize_callback'=>'esc_url_raw'));$wp_customize->add_control('avtospa_telegram',array('label'=>'Telegram URL','section'=>'avtospa_contacts','type'=>'url'));} add_action('customize_register','avtospa_customize_register');
function avtospa_phone_href(){return preg_replace('/[^0-9+]/','',(string)get_theme_mod('avtospa_phone','+7 916 299-98-59'));}
function avtospa_fallback_menu(){echo '<ul><li><a href="'.esc_url(home_url('/#services')).'">Услуги</a></li><li><a href="'.esc_url(home_url('/#engine-wash')).'">Мойка двигателя</a></li><li><a href="'.esc_url(home_url('/#tire-service')).'">Шиномонтаж</a></li><li><a href="'.esc_url(home_url('/#contacts')).'">Контакты</a></li></ul>';}
function avtospa_has_seo_plugin(){return defined('WPSEO_VERSION')||defined('AIOSEO_VERSION')||class_exists('RankMath');}
function avtospa_head_seo(){if(avtospa_has_seo_plugin()){return;}if(is_front_page()||is_home()){echo '<meta name="description" content="'.esc_attr('АвтоСпа в Москве — автомойка, мойка двигателя и шиномонтаж. Полярный проезд, 18, стр. 2. Запись и контакты на сайте.').'">\n';}} add_action('wp_head','avtospa_head_seo',2);
function avtospa_schema(){if(!is_front_page()){return;}$phone=get_theme_mod('avtospa_phone','+7 916 299-98-59');$address=get_theme_mod('avtospa_address','Россия, Москва, Полярный проезд, 18, стр. 2');$data=array('@context'=>'https://schema.org','@type'=>'LocalBusiness','name'=>'АвтоСпа','url'=>home_url('/'),'telephone'=>$phone,'address'=>array('@type'=>'PostalAddress','streetAddress'=>$address,'addressLocality'=>'Москва','addressCountry'=>'RU'),'hasOfferCatalog'=>array('@type'=>'OfferCatalog','name'=>'Услуги АвтоСпа','itemListElement'=>array(array('@type'=>'Offer','itemOffered'=>array('@type'=>'Service','name'=>'Автомойка')),array('@type'=>'Offer','itemOffered'=>array('@type'=>'Service','name'=>'Мойка двигателя')),array('@type'=>'Offer','itemOffered'=>array('@type'=>'Service','name'=>'Шиномонтаж')))));foreach(array('avtospa_whatsapp','avtospa_telegram') as $field){$url=get_theme_mod($field,'');if($url){$data['sameAs'][]=esc_url_raw($url);}}echo '<script type="application/ld+json">'.wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).'</script>\n';} add_action('wp_head','avtospa_schema',20);